### PR TITLE
introduce ADT methods

### PR DESCRIPTION
**Pull request by andyglow**
adt methods are the `default` methods defined at Spec (interface) that's being copied over to the base adt class.

### CODE REVIEW

**Comment by andyglow** [comment]
hello @pettermahlen 
please take a look at the change and the idea it implements. would you be open to accept it?

**Comment by pettermahlen** [comment]
This also looks useful, could you update it so it works with #38, then I will merge it as well.

**Comment by andyglow** [comment]
@pettermahlen done. please at your convenience take another look

**Review by pettermahlen — APPROVED** [review]
Looks great, thanks!

**Comment by pettermahlen** [comment]
@andyglow it turns out that merging this has led to maven compilation failing. It's because the `import com.sun.source.util.Trees` statements (and others, I guess) fail to find classes formerly located in tools.jar. I haven't used Maven a lot in many years, and an hour or so of googling for solutions hasn't really helped. Is this something that you can help fix? If not, releasing will be hard.

**Comment by andyglow** [comment]
Well. I'm not a maven guy as well. But my research revealed that it gets compiled fine if you use Java up to 11. For Java 17 we need to specify a bunch of compiler options to allow unnamed modules access jdk.compile module. I couldn't find a way to make maven conditionally (if Java version is greater then X) apply compiler options. If applied non conditionally then compilation failed for java versions less then  or equal to 11.

**Comment by andyglow** [comment]
Can you build it with Java 11?

**Comment by pettermahlen** [comment]
I am using Java 11: `openjdk version "11.0.15" 2022-04-19 LTS`.

**Comment by andyglow** [comment]
can you share logs please?

this is the version of java that I used to compile it
```
> java -version         
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Homebrew (build 11.0.19+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.19+0, mixed mode)
```

**Comment by pettermahlen** [comment]
The relevant bits are 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dataenum-processor: Compilation failure: Compilation failure:
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/MethodParser.java:[28,27] package com.sun.source.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/MethodParser.java:[39,56] cannot find symbol
[ERROR]   symbol:   class Trees
[ERROR]   location: class com.spotify.dataenum.processor.parser.MethodParser
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/ProcessingContext.java:[24,27] package com.sun.source.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/ProcessingContext.java:[32,16] cannot find symbol
[ERROR]   symbol:   class Trees
[ERROR]   location: class com.spotify.dataenum.processor.ProcessingContext
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/DataEnumProcessor.java:[36,27] package com.sun.source.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/DataEnumProcessor.java:[47,11] cannot find symbol
[ERROR]   symbol:   class Trees
[ERROR]   location: class com.spotify.dataenum.processor.DataEnumProcessor
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/MembersParser.java:[25,32] package com.sun.tools.javac.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/MembersParser.java:[44,10] cannot find symbol
[ERROR]   symbol:   class Pair
[ERROR]   location: class com.spotify.dataenum.processor.parser.MembersParser
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/SpecParser.java:[28,32] package com.sun.tools.javac.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[24,27] package com.sun.source.tree does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[25,27] package com.sun.source.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[26,27] package com.sun.source.util does not exist
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[62,63] cannot find symbol
[ERROR]   symbol:   class Trees
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[69,45] cannot find symbol
[ERROR]   symbol:   class TreePathScanner
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[71,28] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[73,35] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[77,74] cannot find symbol
[ERROR]   symbol:   class Trees
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[77,19] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[89,29] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/ProcessingContext.java:[37,18] cannot find symbol
[ERROR]   symbol:   variable Trees
[ERROR]   location: class com.spotify.dataenum.processor.ProcessingContext
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/DataEnumProcessor.java:[52,18] cannot find symbol
[ERROR]   symbol:   variable Trees
[ERROR]   location: class com.spotify.dataenum.processor.DataEnumProcessor
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/MembersParser.java:[112,15] cannot find symbol
[ERROR]   symbol:   class Pair
[ERROR]   location: class com.spotify.dataenum.processor.parser.MembersParser
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/parser/SpecParser.java:[60,11] cannot find symbol
[ERROR]   symbol:   class Pair
[ERROR]   location: class com.spotify.dataenum.processor.parser.SpecParser
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[63,11] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[80,23] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[82,7] cannot find symbol
[ERROR]   symbol:   class MethodTree
[ERROR]   location: class com.spotify.dataenum.processor.generator.method.MethodMethods.MethodLookup
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[88,5] method does not override or implement a method from a supertype
[ERROR] /Users/petter/opensource/dataenum/dataenum-processor/src/main/java/com/spotify/dataenum/processor/generator/method/MethodMethods.java:[91,14] non-static variable super cannot be referenced from a static context
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dataenum-processor
```

**Comment by pettermahlen** [comment]
That was from `mvn verify` in the root. 

Also, full version output from `java -version`: 
```
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Corretto-11.0.15.9.1 (build 11.0.15+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.15.9.1 (build 11.0.15+9-LTS, mixed mode)
```

**Comment by andyglow** [comment]
@pettermahlen i see that you merged it, so you sorted the build issues out?

**Comment by pettermahlen** [comment]
No, unfortunately I merged before I noticed that there was an issue. We don't seem to have CI for this project..

**Comment by andyglow** [comment]
I see. Let me try to build with `corretto`

**Comment by andyglow** [comment]
@pettermahlen did you try to build it with `java8`? 
I have a string filling that it wasn't supposed to be built by `java11`..
I tried to make it buildable by `java11`, but it required a lot of extra exercises with `module.java` stuff.

**Comment by pettermahlen** [comment]
After a long fight with rotten bits, I managed to create and deploy a release. 1.5.0 is now out, thanks for your contributions!

**Pull request merged**
